# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mergedhelp.ui'
#
# Created: Wed Apr 20 13:35:57 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(781, 451)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.stdHomeButton = QtGui.QPushButton(self.tab)
        self.stdHomeButton.setObjectName(_fromUtf8("stdHomeButton"))
        self.horizontalLayout_2.addWidget(self.stdHomeButton)
        self.stdBackButton = QtGui.QPushButton(self.tab)
        self.stdBackButton.setObjectName(_fromUtf8("stdBackButton"))
        self.horizontalLayout_2.addWidget(self.stdBackButton)
        self.stdForwardButton = QtGui.QPushButton(self.tab)
        self.stdForwardButton.setObjectName(_fromUtf8("stdForwardButton"))
        self.horizontalLayout_2.addWidget(self.stdForwardButton)
        self.stdSearchEdit = QtGui.QLineEdit(self.tab)
        self.stdSearchEdit.setObjectName(_fromUtf8("stdSearchEdit"))
        self.horizontalLayout_2.addWidget(self.stdSearchEdit)
        self.stdSearchButton = QtGui.QPushButton(self.tab)
        self.stdSearchButton.setObjectName(_fromUtf8("stdSearchButton"))
        self.horizontalLayout_2.addWidget(self.stdSearchButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeWidget = QtGui.QTreeWidget(self.splitter)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.treeWidget.setToolTip(_fromUtf8(""))
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.textBrowser = QtGui.QTextBrowser(self.splitter)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.stdFindLabel = QtGui.QLabel(self.tab)
        self.stdFindLabel.setObjectName(_fromUtf8("stdFindLabel"))
        self.horizontalLayout_3.addWidget(self.stdFindLabel)
        self.stdFindEdit = QtGui.QLineEdit(self.tab)
        self.stdFindEdit.setObjectName(_fromUtf8("stdFindEdit"))
        self.horizontalLayout_3.addWidget(self.stdFindEdit)
        spacerItem = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.onlHomeButton = QtGui.QPushButton(self.tab_2)
        self.onlHomeButton.setObjectName(_fromUtf8("onlHomeButton"))
        self.horizontalLayout.addWidget(self.onlHomeButton)
        self.onlBackButton = QtGui.QPushButton(self.tab_2)
        self.onlBackButton.setObjectName(_fromUtf8("onlBackButton"))
        self.horizontalLayout.addWidget(self.onlBackButton)
        self.onlForwardButton = QtGui.QPushButton(self.tab_2)
        self.onlForwardButton.setObjectName(_fromUtf8("onlForwardButton"))
        self.horizontalLayout.addWidget(self.onlForwardButton)
        self.onlSearchEdit = QtGui.QLineEdit(self.tab_2)
        self.onlSearchEdit.setObjectName(_fromUtf8("onlSearchEdit"))
        self.horizontalLayout.addWidget(self.onlSearchEdit)
        self.onlSearchButton = QtGui.QPushButton(self.tab_2)
        self.onlSearchButton.setObjectName(_fromUtf8("onlSearchButton"))
        self.horizontalLayout.addWidget(self.onlSearchButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.webView = QtWebKit.QWebView(self.tab_2)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.gridLayout_3.addWidget(self.webView, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.onlFindLabel = QtGui.QLabel(self.tab_2)
        self.onlFindLabel.setObjectName(_fromUtf8("onlFindLabel"))
        self.horizontalLayout_4.addWidget(self.onlFindLabel)
        self.onlFindEdit = QtGui.QLineEdit(self.tab_2)
        self.onlFindEdit.setObjectName(_fromUtf8("onlFindEdit"))
        self.horizontalLayout_4.addWidget(self.onlFindEdit)
        spacerItem1 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHistory = QtGui.QMenu(self.menubar)
        self.menuHistory.setObjectName(_fromUtf8("menuHistory"))
        self.menuView_Complete_History = QtGui.QMenu(self.menuHistory)
        self.menuView_Complete_History.setObjectName(_fromUtf8("menuView_Complete_History"))
        self.menuClear_History = QtGui.QMenu(self.menuHistory)
        self.menuClear_History.setObjectName(_fromUtf8("menuClear_History"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionHome = QtGui.QAction(MainWindow)
        self.actionHome.setObjectName(_fromUtf8("actionHome"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionView_Standard_History = QtGui.QAction(MainWindow)
        self.actionView_Standard_History.setObjectName(_fromUtf8("actionView_Standard_History"))
        self.actionView_Online_History = QtGui.QAction(MainWindow)
        self.actionView_Online_History.setObjectName(_fromUtf8("actionView_Online_History"))
        self.actionClear_Standard_History = QtGui.QAction(MainWindow)
        self.actionClear_Standard_History.setObjectName(_fromUtf8("actionClear_Standard_History"))
        self.actionClear_Online_History = QtGui.QAction(MainWindow)
        self.actionClear_Online_History.setObjectName(_fromUtf8("actionClear_Online_History"))
        self.menuFile.addAction(self.actionHome)
        self.menuFile.addAction(self.actionClose)
        self.menuView_Complete_History.addAction(self.actionView_Standard_History)
        self.menuView_Complete_History.addAction(self.actionView_Online_History)
        self.menuClear_History.addAction(self.actionClear_Standard_History)
        self.menuClear_History.addAction(self.actionClear_Online_History)
        self.menuHistory.addAction(self.menuView_Complete_History.menuAction())
        self.menuHistory.addAction(self.menuClear_History.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHistory.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.stdHomeButton.setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.stdBackButton.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.stdForwardButton.setText(QtGui.QApplication.translate("MainWindow", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.stdSearchButton.setText(QtGui.QApplication.translate("MainWindow", "Search...", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Help Topics", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "Oragami Concepts", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Preparation", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Imaging", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "3D", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(0).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "2D", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("MainWindow", "Cadnano Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Tree View", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Slice View", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Renum", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(1).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(1).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "First/Last", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(1).child(4).setText(0, QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Path View", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "Staple", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Skip", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).child(4).setText(0, QtGui.QApplication.translate("MainWindow", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).child(5).setText(0, QtGui.QApplication.translate("MainWindow", "Force", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).child(6).setText(0, QtGui.QApplication.translate("MainWindow", "Erase", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(2).child(7).setText(0, QtGui.QApplication.translate("MainWindow", "Break", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "Main Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(3).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(3).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(3).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(3).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "SVG", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(3).child(4).setText(0, QtGui.QApplication.translate("MainWindow", "Honeycomb", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(3).child(5).setText(0, QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("MainWindow", "Design Techniques", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("MainWindow", "Glossary", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.stdFindLabel.setText(QtGui.QApplication.translate("MainWindow", "Find:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Standard Help", None, QtGui.QApplication.UnicodeUTF8))
        self.onlHomeButton.setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.onlBackButton.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.onlForwardButton.setText(QtGui.QApplication.translate("MainWindow", "Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.onlSearchButton.setText(QtGui.QApplication.translate("MainWindow", "Search...", None, QtGui.QApplication.UnicodeUTF8))
        self.onlFindLabel.setText(QtGui.QApplication.translate("MainWindow", "Find:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Online Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHistory.setTitle(QtGui.QApplication.translate("MainWindow", "History", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView_Complete_History.setTitle(QtGui.QApplication.translate("MainWindow", "View Complete History", None, QtGui.QApplication.UnicodeUTF8))
        self.menuClear_History.setTitle(QtGui.QApplication.translate("MainWindow", "Clear History", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Standard_History.setText(QtGui.QApplication.translate("MainWindow", "Standard History", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_Online_History.setText(QtGui.QApplication.translate("MainWindow", "Online History", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Standard_History.setText(QtGui.QApplication.translate("MainWindow", "Standard History", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Online_History.setText(QtGui.QApplication.translate("MainWindow", "Online History", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
